version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - '5673:5672'
      - '15673:15672'
    volumes:
      - ./rabbit/lib:/var/lib/rabbitmq/
      - ./rabbit/log:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
  mongodb:
    container_name: mongo-dev
    image: mongo
    restart: unless-stopped
    command: mongod --auth
    networks:
      - mongo-compose-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=bobify
    ports:
      - '27018:27017'
    volumes:
      - mongodb:/data/db
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    networks:
      - mongo-compose-network
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=ihavealongpassword
    ports:
      - '8082:8081'
    volumes:
      - mongodb:/data/db
    restart: unless-stopped

networks:
  rabbitmq_go_net:
    driver: bridge
  mongo-compose-network:
    driver: bridge

volumes:
  mongodb:
    driver: local