version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - '5673:5672'
        - '15673:15672'
    volumes:
        - ./rabbit/lib:/var/lib/rabbitmq/
        - ./rabbit/log:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

  mongodb:
    image : mongo
    container_name: 'mongodb'
    command: mongod --auth
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=Superpasssecret123
        - MONGO_INITDB_DATABASE=auth
    volumes:
      - ./rabbit/mongo:/data/db
    networks:
      - mongodb_network
    ports:
      - '27019:27017'
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: 'mongo-express'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=Superpasssecret123
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    volumes:
      - ./rabbit/mongo:/data/db
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - mongodb_network
    ports:
      - '8082:8081'
    restart: always

volumes:
  mongodb-data:
    name: mongodb-data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/maciejkrosnicki/Documents/Projekty/Moje/BobifyLogs/rabbit/mongo'

networks:
  rabbitmq_go_net:
    driver: bridge
  mongodb_network:
    driver: bridge
