server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
  data:
    mongodb:
      port: 27018
      username: admin
      password: pass
      database: bobify
      auto-index-creation: true
      authentication-database: admin